name = "project_phoebe"
author = "Slimeist"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "303e8154265d5594a0c7b5a320ce552074eb2ec367fa8e3ba09beedbb81a7c6b"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
