name = "project_phoebe"
author = "Slimeist"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b58dfe8d3c61b6ca76651cd72cc27becdd69fe506a93916a1e1a1cfecd88cb3"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
