name = "project_phoebe"
author = "Slimeist"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12053be3e3c20a80672a888ff40030cb9af9402d12e08508e112d9edb03b1e80"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
